MIXAMO_PREFIX = "mixamorig:"

DEFAULT_BONE_MAPPING = {
    "Hips": "mixamorig:Hips",
    "Spine": "mixamorig:Spine",
    "Spine1": "mixamorig:Spine1",
    "Spine2": "mixamorig:Spine2",
    "Neck": "mixamorig:Neck",
    "Head": "mixamorig:Head",
    "LeftShoulder": "mixamorig:LeftShoulder",
    "LeftArm": "mixamorig:LeftArm",
    "LeftForeArm": "mixamorig:LeftForeArm",
    "LeftHand": "mixamorig:LeftHand",
    "LeftHandThumb1": "mixamorig:LeftHandThumb1",
    "LeftHandThumb2": "mixamorig:LeftHandThumb2",
    "LeftHandThumb3": "mixamorig:LeftHandThumb3",
    "LeftHandIndex1": "mixamorig:LeftHandIndex1",
    "LeftHandIndex2": "mixamorig:LeftHandIndex2",
    "LeftHandIndex3": "mixamorig:LeftHandIndex3",
    "LeftHandMiddle1": "mixamorig:LeftHandMiddle1",
    "LeftHandMiddle2": "mixamorig:LeftHandMiddle2",
    "LeftHandMiddle3": "mixamorig:LeftHandMiddle3",
    "LeftHandRing1": "mixamorig:LeftHandRing1",
    "LeftHandRing2": "mixamorig:LeftHandRing2",
    "LeftHandRing3": "mixamorig:LeftHandRing3",
    "LeftHandPinky1": "mixamorig:LeftHandPinky1",
    "LeftHandPinky2": "mixamorig:LeftHandPinky2",
    "LeftHandPinky3": "mixamorig:LeftHandPinky3",
    "RightShoulder": "mixamorig:RightShoulder",
    "RightArm": "mixamorig:RightArm",
    "RightForeArm": "mixamorig:RightForeArm",
    "RightHand": "mixamorig:RightHand",
    "RightHandThumb1": "mixamorig:RightHandThumb1",
    "RightHandThumb2": "mixamorig:RightHandThumb2",
    "RightHandThumb3": "mixamorig:RightHandThumb3",
    "RightHandIndex1": "mixamorig:RightHandIndex1",
    "RightHandIndex2": "mixamorig:RightHandIndex2",
    "RightHandIndex3": "mixamorig:RightHandIndex3",
    "RightHandMiddle1": "mixamorig:RightHandMiddle1",
    "RightHandMiddle2": "mixamorig:RightHandMiddle2",
    "RightHandMiddle3": "mixamorig:RightHandMiddle3",
    "RightHandRing1": "mixamorig:RightHandRing1",
    "RightHandRing2": "mixamorig:RightHandRing2",
    "RightHandRing3": "mixamorig:RightHandRing3",
    "RightHandPinky1": "mixamorig:RightHandPinky1",
    "RightHandPinky2": "mixamorig:RightHandPinky2",
    "RightHandPinky3": "mixamorig:RightHandPinky3",
    "LeftUpLeg": "mixamorig:LeftUpLeg",
    "LeftLeg": "mixamorig:LeftLeg",
    "LeftFoot": "mixamorig:LeftFoot",
    "LeftToeBase": "mixamorig:LeftToeBase",
    "RightUpLeg": "mixamorig:RightUpLeg",
    "RightLeg": "mixamorig:RightLeg",
    "RightFoot": "mixamorig:RightFoot",
    "RightToeBase": "mixamorig:RightToeBase",
}

CRITICAL_BONES = {
    "mixamorig:Hips", "mixamorig:Spine", "mixamorig:Neck", "mixamorig:Head",
    "mixamorig:LeftUpLeg", "mixamorig:LeftLeg", "mixamorig:LeftFoot",
    "mixamorig:RightUpLeg", "mixamorig:RightLeg", "mixamorig:RightFoot",
    "mixamorig:LeftArm", "mixamorig:LeftForeArm", "mixamorig:LeftHand",
    "mixamorig:RightArm", "mixamorig:RightForeArm", "mixamorig:RightHand",
}

SECONDARY_BONES = {
    "mixamorig:Spine1", "mixamorig:Spine2", "mixamorig:LeftShoulder", "mixamorig:RightShoulder",
    "mixamorig:LeftToeBase", "mixamorig:RightToeBase",
}

OPTIONAL_BONE_KEYWORDS = ("Thumb", "Index", "Middle", "Ring", "Pinky")

MIXAMO_BONE_HIERARCHY = {
    "mixamorig:Hips": ["mixamorig:Spine", "mixamorig:LeftUpLeg", "mixamorig:RightUpLeg"],
    "mixamorig:Spine": ["mixamorig:Spine1"],
    "mixamorig:Spine1": ["mixamorig:Spine2"],
    "mixamorig:Spine2": ["mixamorig:Neck", "mixamorig:LeftShoulder", "mixamorig:RightShoulder"],
    "mixamorig:Neck": ["mixamorig:Head"],
    "mixamorig:LeftShoulder": ["mixamorig:LeftArm"],
    "mixamorig:LeftArm": ["mixamorig:LeftForeArm"],
    "mixamorig:LeftForeArm": ["mixamorig:LeftHand"],
    "mixamorig:LeftHand": ["mixamorig:LeftHandThumb1", "mixamorig:LeftHandIndex1", "mixamorig:LeftHandMiddle1", "mixamorig:LeftHandRing1", "mixamorig:LeftHandPinky1"],
    "mixamorig:LeftHandThumb1": ["mixamorig:LeftHandThumb2"],
    "mixamorig:LeftHandThumb2": ["mixamorig:LeftHandThumb3"],
    "mixamorig:LeftHandIndex1": ["mixamorig:LeftHandIndex2"],
    "mixamorig:LeftHandIndex2": ["mixamorig:LeftHandIndex3"],
    "mixamorig:LeftHandMiddle1": ["mixamorig:LeftHandMiddle2"],
    "mixamorig:LeftHandMiddle2": ["mixamorig:LeftHandMiddle3"],
    "mixamorig:LeftHandRing1": ["mixamorig:LeftHandRing2"],
    "mixamorig:LeftHandRing2": ["mixamorig:LeftHandRing3"],
    "mixamorig:LeftHandPinky1": ["mixamorig:LeftHandPinky2"],
    "mixamorig:LeftHandPinky2": ["mixamorig:LeftHandPinky3"],
    "mixamorig:RightShoulder": ["mixamorig:RightArm"],
    "mixamorig:RightArm": ["mixamorig:RightForeArm"],
    "mixamorig:RightForeArm": ["mixamorig:RightHand"],
    "mixamorig:RightHand": ["mixamorig:RightHandThumb1", "mixamorig:RightHandIndex1", "mixamorig:RightHandMiddle1", "mixamorig:RightHandRing1", "mixamorig:RightHandPinky1"],
    "mixamorig:RightHandThumb1": ["mixamorig:RightHandThumb2"],
    "mixamorig:RightHandThumb2": ["mixamorig:RightHandThumb3"],
    "mixamorig:RightHandIndex1": ["mixamorig:RightHandIndex2"],
    "mixamorig:RightHandIndex2": ["mixamorig:RightHandIndex3"],
    "mixamorig:RightHandMiddle1": ["mixamorig:RightHandMiddle2"],
    "mixamorig:RightHandMiddle2": ["mixamorig:RightHandMiddle3"],
    "mixamorig:RightHandRing1": ["mixamorig:RightHandRing2"],
    "mixamorig:RightHandRing2": ["mixamorig:RightHandRing3"],
    "mixamorig:RightHandPinky1": ["mixamorig:RightHandPinky2"],
    "mixamorig:RightHandPinky2": ["mixamorig:RightHandPinky3"],
    "mixamorig:LeftUpLeg": ["mixamorig:LeftLeg"],
    "mixamorig:LeftLeg": ["mixamorig:LeftFoot"],
    "mixamorig:LeftFoot": ["mixamorig:LeftToeBase"],
    "mixamorig:RightUpLeg": ["mixamorig:RightLeg"],
    "mixamorig:RightLeg": ["mixamorig:RightFoot"],
    "mixamorig:RightFoot": ["mixamorig:RightToeBase"],
}
