import math

import bpy

"""VRM humanoid body-only target profile.

This profile maps the existing Mixamo intermediate skeleton produced by the
BVH pipeline onto a VRM 0.x humanoid armature using only body bones. Secondary
VRM bones such as hair, skirt, sleeve, hood strings, colliders, and spring-bone
chains are intentionally ignored.
"""

TARGET_VRM_BODY = 'VRM_BODY'

# Source is the stable internal Mixamo-style skeleton generated by the addon.
# Target is the common UniVRM/VRoid J_Bip_* humanoid body naming used by the
# provided VRM model.
MIXAMO_TO_VRM_BODY = {
    'mixamorig:Hips': 'J_Bip_C_Hips',
    'mixamorig:Spine': 'J_Bip_C_Spine',
    'mixamorig:Spine1': 'J_Bip_C_Chest',
    'mixamorig:Spine2': 'J_Bip_C_UpperChest',
    'mixamorig:Neck': 'J_Bip_C_Neck',
    'mixamorig:Head': 'J_Bip_C_Head',

    'mixamorig:LeftShoulder': 'J_Bip_L_Shoulder',
    'mixamorig:LeftArm': 'J_Bip_L_UpperArm',
    'mixamorig:LeftForeArm': 'J_Bip_L_LowerArm',
    'mixamorig:LeftHand': 'J_Bip_L_Hand',
    'mixamorig:RightShoulder': 'J_Bip_R_Shoulder',
    'mixamorig:RightArm': 'J_Bip_R_UpperArm',
    'mixamorig:RightForeArm': 'J_Bip_R_LowerArm',
    'mixamorig:RightHand': 'J_Bip_R_Hand',

    'mixamorig:LeftUpLeg': 'J_Bip_L_UpperLeg',
    'mixamorig:LeftLeg': 'J_Bip_L_LowerLeg',
    'mixamorig:LeftFoot': 'J_Bip_L_Foot',
    'mixamorig:LeftToeBase': 'J_Bip_L_ToeBase',
    'mixamorig:RightUpLeg': 'J_Bip_R_UpperLeg',
    'mixamorig:RightLeg': 'J_Bip_R_LowerLeg',
    'mixamorig:RightFoot': 'J_Bip_R_Foot',
    'mixamorig:RightToeBase': 'J_Bip_R_ToeBase',

    # Fingers are kept in the map for optional hand motion when present, but the
    # profile remains body-only because J_Sec_* secondary bones are excluded.
    'mixamorig:LeftHandThumb1': 'J_Bip_L_Thumb1',
    'mixamorig:LeftHandThumb2': 'J_Bip_L_Thumb2',
    'mixamorig:LeftHandThumb3': 'J_Bip_L_Thumb3',
    'mixamorig:LeftHandIndex1': 'J_Bip_L_Index1',
    'mixamorig:LeftHandIndex2': 'J_Bip_L_Index2',
    'mixamorig:LeftHandIndex3': 'J_Bip_L_Index3',
    'mixamorig:LeftHandMiddle1': 'J_Bip_L_Middle1',
    'mixamorig:LeftHandMiddle2': 'J_Bip_L_Middle2',
    'mixamorig:LeftHandMiddle3': 'J_Bip_L_Middle3',
    'mixamorig:LeftHandRing1': 'J_Bip_L_Ring1',
    'mixamorig:LeftHandRing2': 'J_Bip_L_Ring2',
    'mixamorig:LeftHandRing3': 'J_Bip_L_Ring3',
    'mixamorig:LeftHandPinky1': 'J_Bip_L_Little1',
    'mixamorig:LeftHandPinky2': 'J_Bip_L_Little2',
    'mixamorig:LeftHandPinky3': 'J_Bip_L_Little3',

    'mixamorig:RightHandThumb1': 'J_Bip_R_Thumb1',
    'mixamorig:RightHandThumb2': 'J_Bip_R_Thumb2',
    'mixamorig:RightHandThumb3': 'J_Bip_R_Thumb3',
    'mixamorig:RightHandIndex1': 'J_Bip_R_Index1',
    'mixamorig:RightHandIndex2': 'J_Bip_R_Index2',
    'mixamorig:RightHandIndex3': 'J_Bip_R_Index3',
    'mixamorig:RightHandMiddle1': 'J_Bip_R_Middle1',
    'mixamorig:RightHandMiddle2': 'J_Bip_R_Middle2',
    'mixamorig:RightHandMiddle3': 'J_Bip_R_Middle3',
    'mixamorig:RightHandRing1': 'J_Bip_R_Ring1',
    'mixamorig:RightHandRing2': 'J_Bip_R_Ring2',
    'mixamorig:RightHandRing3': 'J_Bip_R_Ring3',
    'mixamorig:RightHandPinky1': 'J_Bip_R_Little1',
    'mixamorig:RightHandPinky2': 'J_Bip_R_Little2',
    'mixamorig:RightHandPinky3': 'J_Bip_R_Little3',
}

VRM_BODY_CRITICAL = {
    'J_Bip_C_Hips', 'J_Bip_C_Spine', 'J_Bip_C_Chest', 'J_Bip_C_Neck', 'J_Bip_C_Head',
    'J_Bip_L_UpperArm', 'J_Bip_L_LowerArm', 'J_Bip_L_Hand',
    'J_Bip_R_UpperArm', 'J_Bip_R_LowerArm', 'J_Bip_R_Hand',
    'J_Bip_L_UpperLeg', 'J_Bip_L_LowerLeg', 'J_Bip_L_Foot',
    'J_Bip_R_UpperLeg', 'J_Bip_R_LowerLeg', 'J_Bip_R_Foot',
}

VRM_SECONDARY_PREFIXES_TO_IGNORE = ('J_Sec_',)


def get_vrm_body_source_to_target_mapping():
    return MIXAMO_TO_VRM_BODY.copy()


def get_vrm_body_target_to_source_mapping():
    return {target: source for source, target in MIXAMO_TO_VRM_BODY.items()}


def is_vrm_body_armature(armature):
    if not armature or armature.type != 'ARMATURE':
        return False
    bones = set(armature.data.bones.keys())
    return len(VRM_BODY_CRITICAL.intersection(bones)) >= 10


def validate_vrm_body_target(armature):
    bones = set(armature.data.bones.keys()) if armature else set()
    body_targets = set(MIXAMO_TO_VRM_BODY.values())
    matched = sorted(body_targets.intersection(bones))
    missing = sorted(body_targets - bones)
    critical_missing = sorted(VRM_BODY_CRITICAL - bones)
    secondary_count = len([name for name in bones if name.startswith(VRM_SECONDARY_PREFIXES_TO_IGNORE)])
    score = int(100 * len(matched) / max(1, len(body_targets)))
    return {
        'matched_count': len(matched),
        'missing_count': len(missing),
        'critical_missing_count': len(critical_missing),
        'matched': matched,
        'missing': missing,
        'critical_missing': critical_missing,
        'secondary_ignored_count': secondary_count,
        'score': min(score, 100),
        'can_continue': len(critical_missing) == 0,
    }


# Only the thigh bones need their own front/back axis corrected in the current
# VRM test model. Calf/foot/toe are intentionally preserved because rotating the
# thigh alone can otherwise propagate a twist into the child chain.
VRM_THIGH_FRONT_BACK_BONES = (
    'J_Bip_L_UpperLeg', 'J_Bip_R_UpperLeg',
)

# Child chains that must keep their original armature-space matrices after the
# thigh roll is changed. This protects the already-correct calf/foot/toe from a
# parent-roll side effect.
VRM_THIGH_CHILD_CHAINS_TO_PRESERVE = {
    'J_Bip_L_UpperLeg': ('J_Bip_L_LowerLeg', 'J_Bip_L_Foot', 'J_Bip_L_ToeBase'),
    'J_Bip_R_UpperLeg': ('J_Bip_R_LowerLeg', 'J_Bip_R_Foot', 'J_Bip_R_ToeBase'),
}

_VRM_ROLL_BASELINE_PROP = 'bvh2mixamo_vrm_thigh_roll_baseline_v3510'
_VRM_ROLL_APPLIED_PROP = 'bvh2mixamo_vrm_thigh_roll_applied_v3510'


def _serialize_rolls(rolls):
    return ';'.join(f"{name}:{value:.10f}" for name, value in rolls.items())


def _deserialize_rolls(text):
    result = {}
    if not text:
        return result
    for item in str(text).split(';'):
        if ':' not in item:
            continue
        name, value = item.split(':', 1)
        try:
            result[name] = float(value)
        except ValueError:
            pass
    return result


def _capture_edit_bone_state(edit_bone):
    return {
        'matrix': edit_bone.matrix.copy(),
        'head': edit_bone.head.copy(),
        'tail': edit_bone.tail.copy(),
        'roll': float(edit_bone.roll),
        'use_connect': bool(edit_bone.use_connect),
    }


def _restore_edit_bone_state(edit_bone, state):
    # Restore matrix first because it carries the armature-space bone direction
    # and roll. Then restore endpoints/connect flag to keep the chain clean.
    edit_bone.matrix = state['matrix']
    edit_bone.head = state['head']
    edit_bone.tail = state['tail']
    edit_bone.roll = state['roll']
    edit_bone.use_connect = state['use_connect']


def apply_vrm_thigh_front_back_roll_preserve_children(armature, knee_compensation_left_degrees=-45.0, knee_compensation_right_degrees=45.0):
    """Correct thigh front/back roll and compensate the knee seam only.

    Current validated VRM correction state:
    - Overall pose is correct.
    - Calf / foot / toe are correct and must not be disturbed.
    - Knee roll compensation can be asymmetric; left and right values are exposed separately.

    Design:
    1. Set only UpperLeg roll to baseline + 180 degrees.
    2. Apply independent left/right LowerLeg roll compensation at each knee seam.
    3. Preserve Foot / ToeBase armature-space matrices so the already-correct
       foot chain is not twisted by the knee compensation.

    This does not swap left/right legs, does not change the pose direction, and
    does not drive J_Sec_* skirt/hair/cloth helper bones.
    """
    if not armature or armature.type != 'ARMATURE':
        return {
            'changed': [],
            'missing': list(VRM_THIGH_FRONT_BACK_BONES),
            'knee_compensated': [],
            'preserved_children': [],
            'touched_feet_as_target': False,
        }

    previous_active = bpy.context.view_layer.objects.active
    previous_mode = bpy.context.object.mode if bpy.context.object else 'OBJECT'
    changed = []
    missing = []
    knee_compensated = []
    preserved_children = []

    try:
        bpy.ops.object.mode_set(mode='OBJECT')
    except Exception:
        pass

    for obj in bpy.context.scene.objects:
        obj.select_set(False)
    armature.select_set(True)
    bpy.context.view_layer.objects.active = armature

    try:
        bpy.ops.object.mode_set(mode='EDIT')

        # Baseline stores the clean imported VRM edit-bone rolls. All future
        # operations set absolute target rolls from this baseline rather than
        # adding again, preventing repeated-test accumulation.
        baseline = _deserialize_rolls(armature.get(_VRM_ROLL_BASELINE_PROP, ''))
        if not baseline:
            baseline = {}
            for bone_name in (
                'J_Bip_L_UpperLeg', 'J_Bip_R_UpperLeg',
                'J_Bip_L_LowerLeg', 'J_Bip_R_LowerLeg',
                'J_Bip_L_Foot', 'J_Bip_R_Foot',
                'J_Bip_L_ToeBase', 'J_Bip_R_ToeBase',
            ):
                edit_bone = armature.data.edit_bones.get(bone_name)
                if edit_bone:
                    baseline[bone_name] = float(edit_bone.roll)
            armature[_VRM_ROLL_BASELINE_PROP] = _serialize_rolls(baseline)

        # Preserve only the foot/toe chain. LowerLeg is allowed to receive the
        # knee compensation; Foot/ToeBase are restored afterwards so the feet do
        # not start twisting again.
        foot_toe_names = (
            'J_Bip_L_Foot', 'J_Bip_L_ToeBase',
            'J_Bip_R_Foot', 'J_Bip_R_ToeBase',
        )
        foot_toe_states = {}
        for child_name in foot_toe_names:
            edit_bone = armature.data.edit_bones.get(child_name)
            if edit_bone:
                foot_toe_states[child_name] = _capture_edit_bone_state(edit_bone)

        # 1) Thigh front/back axis fix: absolute baseline + 180 degrees.
        for bone_name in VRM_THIGH_FRONT_BACK_BONES:
            edit_bone = armature.data.edit_bones.get(bone_name)
            if edit_bone:
                base_roll = baseline.get(bone_name, float(edit_bone.roll))
                edit_bone.roll = base_roll + math.pi
                changed.append(bone_name)
            else:
                missing.append(bone_name)

        # 2) Knee seam compensation: rotate LowerLeg roll slightly from baseline.
        # Left/right are independent because many VRM mirrored leg rolls need
        # mirrored signs. Defaults provide a balanced starting point and can be
        # adjusted per character in the UI.
        try:
            left_knee_angle = math.radians(float(knee_compensation_left_degrees))
        except Exception:
            left_knee_angle = math.radians(-45.0)
        try:
            right_knee_angle = math.radians(float(knee_compensation_right_degrees))
        except Exception:
            right_knee_angle = math.radians(45.0)

        knee_settings = (
            ('J_Bip_L_LowerLeg', left_knee_angle),
            ('J_Bip_R_LowerLeg', right_knee_angle),
        )
        for bone_name, knee_angle in knee_settings:
            edit_bone = armature.data.edit_bones.get(bone_name)
            if edit_bone:
                base_roll = baseline.get(bone_name, float(edit_bone.roll))
                edit_bone.roll = base_roll + knee_angle
                knee_compensated.append(f'{bone_name}:{math.degrees(knee_angle):.1f}')

        # 3) Restore foot/toe world orientation after lower-leg compensation.
        for child_name, state in foot_toe_states.items():
            edit_bone = armature.data.edit_bones.get(child_name)
            if edit_bone:
                _restore_edit_bone_state(edit_bone, state)
                preserved_children.append(child_name)

        armature[_VRM_ROLL_APPLIED_PROP] = f'upper_leg_180_knee_L{float(knee_compensation_left_degrees):.2f}_R{float(knee_compensation_right_degrees):.2f}_preserve_foot_toe'
    finally:
        try:
            bpy.ops.object.mode_set(mode='OBJECT')
        except Exception:
            pass
        if previous_active and previous_active.name in bpy.data.objects:
            bpy.context.view_layer.objects.active = previous_active
            try:
                if previous_mode != 'OBJECT':
                    bpy.ops.object.mode_set(mode=previous_mode)
            except Exception:
                pass

    return {
        'changed': changed,
        'missing': missing,
        'knee_compensated': knee_compensated,
        'preserved_children': preserved_children,
        'touched_feet_as_target': False,
    }


# Backward-compatible name used by older operator code.
def apply_vrm_leg_roll_180(armature, knee_compensation_left_degrees=-45.0, knee_compensation_right_degrees=45.0, knee_compensation_degrees=None):
    # Compatibility: older callers may still pass one global knee_compensation_degrees.
    # New path uses independent left/right values.
    if knee_compensation_degrees is not None:
        knee_compensation_left_degrees = knee_compensation_degrees
        knee_compensation_right_degrees = knee_compensation_degrees
    return apply_vrm_thigh_front_back_roll_preserve_children(
        armature,
        knee_compensation_left_degrees=knee_compensation_left_degrees,
        knee_compensation_right_degrees=knee_compensation_right_degrees,
    )
